### ISSUE TITLE
Revamp virtual artifact system

### ISSUE THREAD

**Issue by dagss** [hashdist/hashdist#58]
There's a system of "virtual build artifacts" (or "human-made package interface identifiers") which lets you do

```
"build" : {
    "import": [
        {"ref": "ZLIB", "virtual:zlib/1.2.x"},
    ...
```

rather than having to give a concrete artifact id like `zlib/x6gwbwls6ggmizp2r7vljmkbkxvibbsz`.

Currently the way this works is that the user of the API must provide a dict `virtuals` which maps from the virtual to the physical build artifact. This dict is also propagated to the build environment through the HDIST_VIRTUALS environment variable.

This works ok if the purpose is

**Purpose A)** Control the hashing to avoid rebuilds if the build dependency didn't significantly change.

However, to provide binary build artifacts, we also want to use this for

**Purpose B)** Make sure that artifacts are relocateable, that a dependency on "zlib 1.2" is really that.

A "transient" setup of the virtuals doesn't work in this case since the real path will still end up in RPATH.

So instead we need something similar to Debian's `/etc/alternatives`, e.g.:

```
opt/zlib/x6gw
opt/zlib/km4f
opt/zlib/virtual-1.2.x -> x6gw
opt/zlib/virtual-1.2.6 -> x6gw
opt/zlib/virtual-1.2.7 -> km4f
opt/zlib/virtual-1.2.8 -> ../forked-of-zlib-with-same-abi/as5f
```

**Tasks**
- [ ] Add an API to BuildStore like `register_virtual` and `resolve_virtual`
- [ ] When setting up build environment (`hashdist/core/run_job.py`), the virtual build artifacts should not really be resolved, but just their appropriate symlink inserted in the environment directly
- [ ] Remove the `virtuals` dict and `HDIST_VIRTUAL` env-var

**Versioning consideration**

Assume you first do

```
build_store.register_virtual("zlib/x6gwbwls6ggmizp2r7vljmkbkxvibbsz", ["virtual:zlib/1.2.x", "virtual:zlib/1.2.7"])
```

and then

```
build_store.register_virtual("zlib/xzdbudgr7wqffju4h7mu7dhv634gv6ru", ["virtual:zlib/1.2.x", "virtual:zlib/1.2.6"])
```

What should happen?

It would be possible to punt on this for now, and have `register_virtual` either always overwrite, or always let any existing links be (after all "1.2.6" is a valid "1.2.x").

But an alternative would be to use version comparison. In that case, we specify that every build artifact must specify a PEP 386 or semver version:
- PEP 386: http://www.python.org/dev/peps/pep-0386/
- semver: http://semver.org/

That would be required in `build.json` and automatically carried over to `artifact.json`. Then, the behaviour of `register_virtual()` is to let the highest version win (and probably overwrite if it is a tie).

Finally, the garbage collector (which is not started on yet) could have the liberty to switch virtuals around to free up disk space while still satisfying requirements. That would require keeping a list of "potential candidates for a virtual", even if only one is active as a symlink.

**Names:**

The hashes will never contain `-`, so the filesystem scheme above is always collision-free. I wonder if we should change the syntax, e.g., `zlib/virtual-1.2.x` rather than `virtual:zlib/1.2.x`. I'm open to better names than virtual too. "abi" works in this specific case but there are other cases, such as `virtual:unix`, which is a dependency on `cp`, `mv`, etc., without being an ABI. Perhaps "api" is general enough;

```
"build" : {
    "import": [
        {"ref": "UNIX", "unix/api-r1"},
        {"ref": "ZLIB", "zlib/api-1.2.x"},
        {"ref": "PYTHON", "python/xcelfgbgxnj5yuyug7tsg44dqpmdhg2w"},
    ...
```

and

```
opt/zlib/km4f
opt/zlib/api-1.2.x -> km4f
```

I think I like this... in that case, every reference to "virtual build artifacts" should be replaced with another term...hmmm...
