### ISSUE TITLE
Grep through artifact for dependency artifact paths

### ISSUE THREAD

**Issue by dagss** [hashdist/hashdist#74]
The artifacts should be grepped for the paths of the build dependencies. The purpose is to:
- Record the "hard" run-time dependencies (what is in `build.json` are the build-time dependencies and we can auto-find the hard run-time dependencies)
- In preparation for #58, because we can then warn if a dependency that is virtual ended up being resolved to its realpath.
- Useful diagnostics
### Tasks
- [ ] Benchmark difference between Python re on large mmap-ed binary files and calling `grep -F` (which is an extra nuisance on Windows), and whether it matters
- [ ] Create a tool in `build_tools.py` to grep a directory for the paths of a set of artifact IDs (the build dependencies). Search for both absolute paths and paths relative to a given directory (`$ARTIFACT`), and report which ones is found for each artifact.
- [ ] Add a flag to `hit build-postprocess` which greps the artifact directory (using the `$GREP` environment variable if the `grep -F` path is chosen) and figures out which of the build-time dependencies are also hard run-time dependencies (e.g., zlib for hdf5), and writes those out in a section in `artifact.json`. **Exclude `build.json`**.
- [ ] Add flags `--warning-absolute` and `--error-absolute` to the same tool which warns if the full path, rather than just the relative path, is found. Mainly useful after #13 is fixed though.
